#cloud-config
package_update: true
package_upgrade: true
packages:
  - git
  - python3-pip
  - sshpass
  - ansible
  - python3-yaml
  - docker.io

runcmd:
  - cd /home/ubuntu
  - git clone https://github.com/kubernetes-sigs/kubespray.git
  - cd kubespray
  - pip3 install -r requirements.txt
  - chown -R ubuntu:ubuntu /home/ubuntu/kubespray
  - echo "Kubespray готов на Bastion-хосте" > /home/ubuntu/READY
  - |
    docker login --username oauth --password $(yc iam create-token) cr.yandex
