apiVersion: v1
kind: Service
metadata:
  name: test-nginx-service
  namespace: default
spec:
  type: NodePort
  externalTrafficPolicy: Cluster
  selector:
    app: test-nginx-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
